Repository citycide/glob, pull requests merged in 2020-11, with the labels that each got.

#48 Run tests in a temporary directory
  tests.nim
Labels: type: test

#52 ci(github): rewrite test action and re-enable macOS
  .github/workflows/test.yml
Labels: type: ci

#53 refactor: require nim v1.x
  glob.nimble
  src/glob.nim
Labels: breaking

#54 Use GitHub action to automate releases
  .github/workflows/release.yml
  glob.nimble
  readme.md
Labels: type: ci
